#!/bin/bash

# source -> chache -> destination

source /etc/fotup/conf
# keep checking for sd card with fotos
mkdir -p "$CACHEPATH" /mnt/fotup
while true; do
  sleep 2
  if [[ ! -d "$SDPATH" ]]; then continue; fi
  rsync -Pavz "$SOURCEPATH" "$CACHEPATH" # cache
  sshfs "$DESTINATIONHOST":"$DESTINATIONPATH" /mnt/fotup
  /opt/fotup/fotup-sort "$CACHEPATH" /mnt/fotup
  sync
  umount "$SDPATH"
  sleep 10
done
