#!/bin/bash

apt update && apt install exfat-fuse exfat-utils exiftool ssh sshfs
mkdir -p /etc/fotup /opt/fotup
cp -v detectd sort /opt/fotup
cp -v conf /etc/fotup
cp -v service /lib/systemd/system/fotup.service
systemctl enable fotup.service
systemctl start fotup.service
