#!/bin/bash

if [[ "$1" == "" ]] || [[ "$2" == "" ]]; then exit 1; fi
SOURCEPATH="$1"
DESTINATIONPATH="$2"

IFS=$'\n'
for f in `find "$SOURCEPATH" -iname *.JPG -o -iname *.CR2 -o -iname *.MP4 -o -iname *.MOV`; do
  DATE=`exiftool "$f" | grep -m 1 "Create Date"`
  if ! echo "$DATE" | grep "Create Date" >/dev/null; then echo "SKIP: no 'Create Date' in exif ($f)"; continue; fi
  YEAR=`echo $DATE | cut -d':' -f2 | cut -c 2-`
  MONTH=`echo $DATE | cut -d':' -f3`
  DAY=`echo $DATE | cut -d':' -f4 | cut -d' ' -f1`
  HOUR=`echo $DATE | cut -d':' -f4 | cut -d' ' -f2`
  MINUTE=`echo $DATE | cut -d':' -f5`
  SECOND=`echo $DATE | cut -d':' -f6`
  HASH=`sha256sum "$f" | cut -d':' -f2 | head -c 3`
  EXT=`basename "$f" | cut -d'.' -f2 | tr '[:upper:]' '[:lower:]'`
  if [[ "$EXT" = "cr2" ]]; then RAW="raw/"; else RAW=""; fi
  FILE="$DESTINATIONPATH/$YEAR-$MONTH/$RAW$YEAR$MONTH$DAY"-"$HOUR$MINUTE$SECOND"_"$HASH"."$EXT"
  mkdir -p "$(dirname "$FILE")"
  mv -v "$f" "$FILE"
done
